const constants = {
     "FETCH_MEMBER_REQUEST" : "COMMAND/FETCH_MEMBER_REQUEST",
     "FETCH_MEMBER_SUCCESS" : "EVENT/FETCH_MEMBER_SUCCESS",
     "LOGIN_USER_REQUEST":  "COMMAND/LOGIN_USER_REQUEST",
     "LOGIN_USER_SUCCESS":  "COMMAND/LOGIN_USER_SUCCESS",
     
  };
  
  export default constants;